### ISSUE TITLE
0.0.26 - wandb sync raises exception when trying to sync TF event files

### ISSUE THREAD

**Issue by douglasrizzo** [wandb/client-ng#23]
I have multiple TensorBoard event files, which were created with PyTorch. I am on Linux. When I run `wandb sync` and point to a TF event file, I get the error reported below. [This](https://github.com/wandb/client/issues/1051) is the error I got when using the current-gen wandb client. These are the versions of things I'm running.

- Manjaro Linux 20.0.3 Lysia
- Python 3.7.7
- wandb client 0.0.26
- tensorboard 2.2.2
- tensorflow 2.2.0
- torch 1.5.0

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/dodo/.anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/dodo/.anaconda3/lib/python3.7/site-packages/wandb/sync/sync.py", line 37, in run
    ds.open_for_scan(sync_item)
  File "/home/dodo/.anaconda3/lib/python3.7/site-packages/wandb/internal/datastore.py", line 98, in open_for_scan
    self._read_header()
  File "/home/dodo/.anaconda3/lib/python3.7/site-packages/wandb/internal/datastore.py", line 165, in _read_header
    raise Exception("Invalid header")
Exception: Invalid header

**Comment by raubitsj** [comment]
Thanks @douglasrizzo for the report.

Currently we only support syncing runs with the `wandb sync` command that were already executed with the wandb library integration but the files were stored locally.   For instance, if you ran while not connected to the internet.

I would like track this bug as a feature request as I think this would be a useful feature to directly sync a TFevent file into wandb.  We have the code to do this, we would just need to do more testing to support this.

**Comment by douglasrizzo** [comment]
Thanks for the quick reply. I read the documentation in [this page](https://docs.wandb.com/library/integrations/tensorboard#syncing-previous-tensorboard-runs), which said:

>If you have existing experiments you would like to import into wandb, you can run `wandb sync log_dir` where log_dir is a local directory containing the tfevents files.

I interpreted that as wandb being able to import any TF event files, not just the ones generated with wandb integration. If you don't mind, I'll suggest a small pull request to the documentation to make that a little more clear.
