### ISSUE TITLE
wandb-ng 0.0.34 broken pipe error on start

### ISSUE THREAD

**Issue by vukovicnikola** [wandb/client-ng#71]
```
wandb: Currently logged in as: nikola (use `wandb login --relogin` to force relogin)
except handle
Traceback (most recent call last):
  File ".\main.py", line 195, in <module>
    best_model = train_model(model, criterion, optimizer, scheduler, num_epochs=config['epochs'])
  File ".\main.py", line 112, in train_model
    for inputs, labels in dataloaders[phase]:
  File "C:\Users\nikola\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\nikola\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\nikola\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\nikola\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\nikola\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\nikola\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\nikola\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by vanpelt** [comment]
Hey @vukovicnikola are you able to share a sample script that causes this to happen in your environment?
